import { createCosmeticTheme } from './cosmetic-theme';
import { haptic } from './feedback';
import { allPairsMatched, createPairDeck, type PairCard } from './game/pairs';
import { readStoredNumber, storageKey, writeStoredNumber } from './platform';

const BEST_TIME_KEY = storageKey('pairs', 'best-time'); const BEST_MOVES_KEY = storageKey('pairs', 'best-moves'); const COMPLETIONS_KEY = storageKey('pairs', 'completions');
const boardElement = document.querySelector<HTMLElement>('#pairs-board')!; const movesElement = document.querySelector<HTMLOutputElement>('#pairs-moves')!; const timeElement = document.querySelector<HTMLOutputElement>('#pairs-time')!; const overlay = document.querySelector<HTMLElement>('#pairs-overlay')!; const result = document.querySelector<HTMLElement>('#pairs-result')!; const eventElement = document.querySelector<HTMLElement>('#pairs-event')!;
let deck: PairCard[] = createPairDeck(); let selected: number[] = []; let matched = new Set<number>(); let moves = 0; let seconds = 0; let resolving = false; let won = false; let completions = readStoredNumber(COMPLETIONS_KEY); let bestTime = readStoredNumber(BEST_TIME_KEY); let bestMoves = readStoredNumber(BEST_MOVES_KEY); let eventTimer: number | undefined;
const showEvent = (message: string): void => { eventElement.textContent = message; eventElement.hidden = false; if (eventTimer !== undefined) window.clearTimeout(eventTimer); eventTimer = window.setTimeout(() => { eventElement.hidden = true; }, 1150); };
const themes = createCosmeticTheme(document.querySelector<HTMLButtonElement>('#pairs-theme')!, 'chocolate-ice-blue', showEvent);
const formatTime = (value: number): string => `${Math.floor(value / 60)}:${String(value % 60).padStart(2, '0')}`;
const restoreThemes = (): void => themes.restore(completions >= 1, completions >= 3);
const render = (): void => { boardElement.replaceChildren(...deck.map((card, index) => { const revealed = selected.includes(index) || matched.has(index); const button = document.createElement('button'); button.type = 'button'; button.className = `pair-card${revealed ? ' is-revealed' : ''}${matched.has(index) ? ' is-matched' : ''}`; button.dataset.index = String(index); button.setAttribute('aria-label', revealed ? `Card ${card.symbol}` : 'Face-down card'); button.textContent = revealed ? card.symbol : '✦'; return button; })); movesElement.value = String(moves); timeElement.value = formatTime(seconds); };
const finish = (): void => { won = true; completions += 1; writeStoredNumber(COMPLETIONS_KEY, completions); if (!bestTime || seconds < bestTime) { bestTime = seconds; writeStoredNumber(BEST_TIME_KEY, bestTime); } if (!bestMoves || moves < bestMoves) { bestMoves = moves; writeStoredNumber(BEST_MOVES_KEY, bestMoves); } if (completions === 1) themes.unlockThemes(); if (completions === 3) themes.unlockShake(); result.textContent = `${formatTime(seconds)} · ${moves} moves · Best ${bestTime ? formatTime(bestTime) : '—'} / ${bestMoves || '—'}`; overlay.hidden = false; haptic('success'); };
const choose = (index: number): void => { if (won || resolving || matched.has(index) || selected.includes(index)) return; selected.push(index); render(); if (selected.length !== 2) return; moves += 1; const [first, second] = selected; if (deck[first].symbol === deck[second].symbol) { matched.add(first); matched.add(second); selected = []; haptic('success'); render(); if (allPairsMatched(matched)) finish(); return; } resolving = true; render(); haptic('impact'); window.setTimeout(() => { selected = []; resolving = false; render(); }, 720); };
const restart = (): void => { deck = createPairDeck(); selected = []; matched = new Set(); moves = 0; seconds = 0; resolving = false; won = false; overlay.hidden = true; restoreThemes(); render(); };
boardElement.addEventListener('click', (event) => { const card = (event.target as HTMLElement).closest<HTMLButtonElement>('.pair-card'); if (card) choose(Number(card.dataset.index)); }); document.querySelectorAll<HTMLButtonElement>('[data-pairs-restart]').forEach((button) => button.addEventListener('click', restart)); window.setInterval(() => { if (!won && !document.hidden) { seconds += 1; timeElement.value = formatTime(seconds); } }, 1000);
restoreThemes(); render();
